# Change these first 
owner: DataByteDigital # Your GitHub organization or username, where this repository lives
repo: status.databytedigital.com # The name of this repository

commitMessages:
  commitAuthorName: "DataByteDigital Bot"
  commitAuthorEmail: "bot@databytedigital.com"

workflowSchedule:
  graphs: "1 */6 * * *"
  responseTime: "1 */6 * * *"
  staticSite: "0 1 * * *"
  summary: "1 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: DataByteDigital - Production
    url: https://databytedigital.com
    maxResponseTime: 5000

  - name: DataByteDigital - Beta
    url: https://beta.databytedigital.com
    icon: https://databytedigital.com/logo.png
    maxResponseTime: 5000

  - name: DataByteDigital - Test
    url: https://test.databytedigital.com
    icon: https://databytedigital.com/logo.png  
    maxResponseTime: 5000

  - name: API
    url: https://api.databytedigital.com
    icon: https://api.databytedigital.com/images/api.png
    maxResponseTime: 5000

  - name: Song Lyrics Studio  
    url: https://songlyrics.databytedigital.com
    maxResponseTime: 5000
    
  - name: Bartalap - Social Network Site
    url: https://bartalap.databytedigital.com
    maxResponseTime: 5000

  - name: Status Page 
    url: https://status.databytedigital.com
    icon: https://databytedigital.com/logo.png
    maxResponseTime: 5000

  - name: Password Generator Service
    url: https://passwordgenerator.databytedigital.com
    maxResponseTime: 5000
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.databytedigital.com
  baseUrl: /status.databytedigital.com
  logoUrl: https://databytedigital.com/logo.png
  favicon: https://databytedigital.com/logo.png
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DataByteDigital
  # introTitle: "Welcome to DataByteDigital.com's home for real-time and historical data on system performance."
  # introMessage: DataByteDigital provides different internet Content related services to the Public. This is the system status for the DataByteDigital services(edge network and dashboard/APIs)
  introMessage: "Welcome to DataByteDigital.com's home for real-time and historical data on system performance."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
